image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: |
    git clone https://github.com/wagtail/wagtail.git
    cd wagtail
    pip install -e '.[testing,docs]' -U
    npm install --no-save
    npm run build
    cd ..
    git clone https://github.com/wagtail/bakerydemo.git
    cd bakerydemo
    cp bakerydemo/settings/local.py.example bakerydemo/settings/local.py
    echo "DJANGO_SETTINGS_MODULE=bakerydemo.settings.local" > .env
    sed -i 's/wagtail>=/# wagtail>=/g' requirements/base.txt
    python -m pip install -r requirements.txt
    python manage.py makemigrations
    python manage.py migrate
    python manage.py load_initial_data
    echo "CSRF_TRUSTED_ORIGINS = ['https://*.gitpod.io']" >> bakerydemo/settings/local.py
  command: >
    python manage.py runserver 0.0.0.0:8080
github:
    prebuilds:
        pullRequestsFromForks: true
vscode:
  extensions:
    - ms-python.python
